FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -yqq && \
    apt-get install -yqq byobu build-essential gcc make cmake cmake-gui cmake-curses-gui \
    fakeroot devscripts dh-make lsb-release \
    libssl-dev doxygen graphviz

RUN git clone https://github.com/eclipse/paho.mqtt.c.git &&\
    cd paho.mqtt.c && make -j $(nproc) && make install
